// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imfsubzcipvzppmeukis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZnN1YnpjaXB2enBwbWV1a2lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTUyNDEsImV4cCI6MjA2ODA5MTI0MX0.XSW9ftr8gaUgoXJShhPRV12y6wOEEkS-6mxqMk7sNlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});